name: sellermultivendor
description: A new Flutter project.

publish_to: "none"
version: 2.7.0+6

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  pinput: ^3.0.1
  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.2
  http: ^0.13.6
  jaguar_jwt: ^3.0.0
  shared_preferences: ^2.0.11
  connectivity_plus: ^4.0.2
  firebase_auth: ^4.2.1
  #cached_network_image: ^3.2.3
  firebase_core: ^2.4.0
  #country_code_picker: ^2.0.2
  intl: ^0.18.0
  flutter_localizations:
    sdk: flutter
  shimmer: ^3.0.0
  url_launcher: ^6.1.7
  sms_autofill: ^2.2.0
  image_picker: ^1.0.1
  fl_chart: ^0.55.2
  file_picker: ^5.2.5
  sticky_headers: ^0.3.0+2
  html_editor_enhanced: ^2.5.1
  mime: ^1.0.3
  lottie: ^2.1.0
  flutter_rating_bar: ^4.0.0
  photo_view: ^0.14.0
  flutter_widget_from_html: ^0.10.0
  provider: ^6.0.5
  google_maps_flutter: ^2.2.2
  geocoding: ^2.0.5
  geolocator: ^10.0.0
  flutter_email_sender: ^6.0.1
  bloc: ^8.1.0
  intl_phone_field: ^3.1.0
  open_filex: ^4.3.2
  external_path: ^1.0.3
  path_provider: ^2.0.14
  firebase_messaging: ^14.1.4
  flutter_local_notifications: ^15.1.0+1

dependency_overrides:
  intl: ^0.18.1
  chewie:
    git:
      url: https://github.com/mdeimert/chewie.git
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  just_audio: ^0.9.30

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animation/
    - lib/Language/
    - assets/images/PNG/
    - assets/images/SVG/

  fonts:
    - family: opensans
      fonts:
        - asset: assets/font/OpenSans-Regular.ttf
